### ISSUE TITLE
Add leetcode.com 

### ISSUE THREAD

**Issue by emli** [AliOsm/kontests#1]

**Comment by AliOsm** [comment]
There is some problems with LeetCode, because of the privacy policy of them, I've contacted them, but they did not response till now, any ideas?

**Comment by emli** [comment]
I think it will no problem. We only parsing data from site

**Comment by AliOsm** [comment]
I've read [this](https://www.quora.com/How-can-I-get-all-leetcode-questions-list-using-API-or-web-scraping/answer/Kevin-Sahin?share=aeafa374&srid=T62d) comment in Quora question, but when I searched for the quoted text in the terms page I didn't find them, so I think there is no problem as you say, I will work on this in the next few days.

**Comment by emli** [comment]
Nice. Good luck @AliOsm

**Comment by AliOsm** [comment]
Hello @emli, I hope you are doing fine
I apologize for being late, LeetCode is supported now, can you check it and confirm?
Thanks!

**Comment by emli** [comment]
Hi @AliOsm !

Ah , cool , I liked it

**Comment by AliOsm** [comment]
Please, let me know if you find any bugs or you want to suggest any new feature.
