### ISSUE TITLE
Request for adding a new site

### ISSUE THREAD

**Issue by Ahasun** [AliOsm/kontests#23]
Could you please add toph.co ?

**Comment by AliOsm** [comment]
I will work on this after doing some refactoring in the project.

**Comment by AliOsm** [comment]
The website added successfully to KONTESTS with some limitations like the incorrect data in end time and duration fields. I will close this issue abd open another one to track the limitations.

Please let me know if you have any other suggestions or if you found any issues with the newly added website.
