### ISSUE TITLE
Pagination Buttons Scroll with Contests Listing

### ISSUE THREAD

**Issue by Git-Harshit** [AliOsm/kontests#25]
#### Problem (Issue) Description:

The Pagination Buttons in "Future Contests" and "Running Contests" Divisions 
![K](https://user-images.githubusercontent.com/57865187/104832749-63b60780-58b9-11eb-807d-8f576466b93b.PNG)
 are scrollable with the table contents, due to which they are prone to get out of the viewable portion.

As an example, consider the long contest name listing below (just used garbage PascalCase Name as an example, but such a situation may arrive anytime in the listing.) 

1. ![KontestsReportCapture-1](https://user-images.githubusercontent.com/57865187/104832990-a5e04880-58bb-11eb-9ef7-585ce59732ca.PNG)

2. ![KontestsReportCapture-2](https://user-images.githubusercontent.com/57865187/104832992-a842a280-58bb-11eb-82e0-149ae6256a02.PNG)

3. ![KontestsReportCapture-3](https://user-images.githubusercontent.com/57865187/104832993-a8db3900-58bb-11eb-8406-3b34aff48791.PNG)

4. ![KontestsReportCapture-4](https://user-images.githubusercontent.com/57865187/104832994-aa0c6600-58bb-11eb-8d6f-aaa2c983c09a.PNG)

5. ![KontestsReportCapture-5](https://user-images.githubusercontent.com/57865187/104832996-ab3d9300-58bb-11eb-9781-ab825ffe3fbe.PNG)

As evident in the above example of running contests, the pagination has gone along with the scroll, in case of a lengthier `IARCS OPC Judge Problems ThisIsaReallyLongGibberishTextJustWrittenToSeeItsImpactOnPrevAndNextButtonsAndSoItTypesJustToFillTheExcessSpaces` name. 

This may cause inconvienience for users to go to Previous and Next buttons for changing pages after scrolling to view the entire contest details. Same is the case for mobile screens.

#### Suggestion(s):

One quick solution for fixing this could be to use the Pagination buttons out of the scrollable boxes, that show the contests tables. 
Another good solution could be to use absolute positioning for the buttons container with reference to `right: <spacing value>;` and setting the divisions `position` as `relative` for absolute position to work in their reference. 

Any more suggestions and solutions are definitely welcome. I hope it'll be fixed soon.

**Comment by AliOsm** [comment]
Hi @Git-Harshit, thanks for the report, I will try the proposed solutions and get back to you soon.

**Comment by AliOsm** [comment]
Solved after >2 months :3
Sorry for being very very very late.
Review this [commit](https://github.com/AliOsm/kontests/commit/e3997b7a784c10bc214f1654d16c08fe4974dfc5) for the solution.
