### ISSUE TITLE
Suggest Site form not working

### ISSUE THREAD

**Issue by Git-Harshit** [AliOsm/kontests#29]
I have just tried to suggest a recent and not so big and famous website for coding named [mycode.prepbytes.com](https://mycode.prepbytes.com/contest) using your site submission suggestion form available under "Supported Sites" dropdown in navbar.
![CaptureKontestsBUGRoot](https://user-images.githubusercontent.com/57865187/115988836-142e5880-a5d9-11eb-98b7-40d9c40e60ea.PNG)

![kontests net_](https://user-images.githubusercontent.com/57865187/115988524-d11fb580-a5d7-11eb-91fe-ef4a8d1ff16b.png)

 But the form didn't respond after hitting the submit button. On inspecting the problem in inspector window, I came across the following error (most possibly due to the absence of jQuery).
![CaptureKontestsBUG](https://user-images.githubusercontent.com/57865187/115988565-fa404600-a5d7-11eb-9239-d647f3b3f322.PNG)

The '$' sign undefined corresponds to the following line of code in the live version of the main site:
![CaptureKontestsBUGDetail](https://user-images.githubusercontent.com/57865187/115988596-1e038c00-a5d8-11eb-86a2-c494311e532d.PNG)

One quick fix for this issue in my knowledge is to include the jQuery library before this line (since it is line 66, how about including jQuery in `<head>` or starting of `<body>` tag).

Please fix this issue at the earliest so that other interesting site suggestions are successfully captured in the future. 🙂

**Comment by AliOsm** [comment]
Hi @Git-Harshit, thanks for your report. Sorry for my late reply, but I was OOO and my access to the email was limited.
I will check this issue and update the issue ASAP.

**Comment by AliOsm** [comment]
Could you imagine that I fixed the issue? I hope that I'm more committed to my projects. Closing the issue, and thanks again for your report.
