### ISSUE TITLE
Is kontests.net down?

### ISSUE THREAD

**Issue by raj454raj** [AliOsm/kontests#43]
<img width="1440" alt="Screenshot 2021-11-27 at 4 49 07 PM" src="https://user-images.githubusercontent.com/6368364/143679059-17489d56-920b-4507-8376-91315f5ce4de.png">

**Comment by AliOsm** [comment]
Hello @raj454raj thanks for creating this.

I just received an email from Heroku team notifies me that my account has been suspended!

I will try to communicate with them to figure out the problem 😪

**Comment by nisarg0** [comment]
Yeah that would be great. Thanks @AliOsm .

**Comment by raj454raj** [comment]
It's up now! Thanks for a quick turnaround @AliOsm! 🎉

**Comment by AliOsm** [comment]
Surprisingly, Heroku team replied to my ticket quickly and unlooked my account and all of my apps come back to life. Still I didn't get a response from them about why that happened.

Thanks @raj454raj and @nisarg0 for taking time to report such a problem and I will be happy to see your commits in the code base 😎✌🏻
