### ISSUE TITLE
Leetcode api is not fetching contest list properly

### ISSUE THREAD

**Issue by mukund0909** [AliOsm/kontests#46]
Leetcode api is not fetching contest list properly

**Comment by nisarg0** [comment]
Yep, @AliOsm can please look into it!

**Comment by AliOsm** [comment]
Checking...
I'm getting better, responding after 2 days only 😎✌🏻

**Comment by AliOsm** [comment]
LeetCode changed their old API https://leetcode.com/contest/api/list to a GraphQL API https://leetcode.com/graphql?query=.

To get all contests list, a query like this should be used:

```graphql
{
  brightTitle
  currentTimestamp
  allContests {
    containsPremium
    title
    cardImg
    titleSlug
    description
    startTime
    duration
    originStartTime
    isVirtual
    company {
      watermark
      __typename
    }
    __typename
  }
}
```

I need some time to do this change, I will keep this issue updated.

**Comment by AliOsm** [comment]
You can use this [link](https://leetcode.com/graphql?query={brightTitle%20currentTimestamp%20allContests%20{%20containsPremium%20title%20cardImg%20titleSlug%20description%20startTime%20duration%20originStartTime%20isVirtual%20company%20{watermark%20__typename}%20__typename}}) to access all contests list.

**Comment by AliOsm** [comment]
Fixed in this [commit](https://github.com/AliOsm/kontests/commit/002ac14d6163b014f1aeea0504f8f9a18d84be5d).
