### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Ahasun** [AliOsm/kontests#6]
First of all thanks for giving us this coolest contest notifier.

![image](https://user-images.githubusercontent.com/32890677/64115837-77d79280-cdb2-11e9-918d-621210bb6486.png)

1year old contest showing in future contest... Please fixed this.

**Comment by AliOsm** [comment]
Hello @Ahasun,

Thank you for alerting us.

The problem was AtCoder website design changed and the crawling script trying to find some HTML elements and it can't.

I fixed the bug and deployed a new version, can you check it and confirm?

**Comment by Ahasun** [comment]
Now Its working fine

**Comment by AliOsm** [comment]
Thanks for your confirmation, please let us know if there is any other issues or suggests.

**Comment by Ahasun** [comment]
Please make Kontest extension for opera mini web browser
