### ISSUE TITLE
REQUEST TO MIGRATE FROM HEROKU.

### ISSUE THREAD

**Issue by mssandeepkamath** [AliOsm/kontests#67]
Hi Ali,
Due to termination of your API service, my app content have stopped. so I kindly request you to host your API on other free platforms.

**Comment by AliOsm** [comment]
Hello @mssandeepkamath , I will start searching for other options, but for now the website will start working after few hours.

**Comment by mssandeepkamath** [comment]
@AliOsm Thanks a lot✨️

**Comment by AliOsm** [comment]
I evaluated multiple options, railway, qoddi, fly.io, ...
No one is providing me the easy setup exists in Heroku.
Anyone wants to support KONTESTS with 5.01$ per month to keep this website alive? Or I should take it down (sadly).
