### ISSUE TITLE
Request to host the API in different platform!!

### ISSUE THREAD

**Issue by RakshithDHegde** [AliOsm/kontests#68]
My website is down due to unavailability of this API. Request you to solve this issue by migrating it to different hosting provider.

**Comment by AliOsm** [comment]
Hello @RakshithDHegde , I will start searching for other hosting platforms, but for now the website will continue working after few hours.

**Comment by RakshithDHegde** [comment]
Thanks a ton🙌

**Comment by AliOsm** [comment]
I evaluated multiple options, railway, qoddi, fly.io, ...
No one is providing me the easy setup exists in Heroku.
Anyone wants to support KONTESTS with 5.01$ per month to keep this website alive? Or I should take it down (sadly).
