### ISSUE TITLE
API not working

### ISSUE THREAD

**Issue by iraunit** [AliOsm/kontests#72]
The website and API are not working now. Will it work in future?

**Comment by kaushikkumarbz** [comment]
https://kontests.herokuapp.com/ 
<img width="1195" alt="image" src="https://user-images.githubusercontent.com/65885903/205132975-493b0b68-a149-4523-88ac-16dae871ff6c.png">

**Comment by AliOsm** [comment]
Hello @iraunit, this happened as Heroku free tier was deprecated. I tried to move KONTESTS to other platforms like railway, but I couldn't. Now, I need support to continue on this. KONTESTS need 5.01$ per month for hosting. If you are willing to support, please let me know.

**Comment by iraunit** [comment]
I am a student so I can't afford it. You can try https://render.com/  or https://www.cyclic.sh/ if railway doesn't work.

**Comment by sahej-dev** [comment]
@AliOsm I am trying to host kontests on https://render.com/ as I use it as data source for a mobile app I developed. I have never touched ruby so hitting a couple of roadblocks. However, if it works I'll inform over here.

**Comment by AliOsm** [comment]
@sahej-dev Thanks for taking care of this, I tried but to be honest without any success. Let us know what happens with you.

**Comment by sahej-dev** [comment]
@AliOsm I've got something working here: https://kontests.onrender.com/. I got it partially working over there a few days ago but the server just stopped responding. Here's to hoping nothing goes wrong this time 🤞.

**Comment by AliOsm** [comment]
Great effort!
Could we have a meeting so we can link the domain with the new hosting and be aware how to publish updates?
My telegram: @aliosm97

**Comment by AliOsm** [comment]
KONTESTS is working again now. I will continue supporting it now until we host it on another free hosting platform, but again, as a community, we need to support the others projects' to be able to build. KONTESTS now needs 10$ per month (Heroku pricing changed), I will continue paying this amount for the next few months, but more than 10 people contacted me about KONTESTS and they built apps/websites on top of it, so they can support it with just 1$ per month to continue their projects.

**Comment by kaushikkumarbz** [comment]
@AliOsm Thanks, It is working as expected now !

**Comment by loyaltytrooper** [comment]
https://qoddi.com/ruby/ @AliOsm

**Comment by nisarg0** [comment]
I'll be happy to contribute if needed @AliOsm . We can connect offline on telegram @nisarg_0.

**Comment by pavan-kalyan** [comment]
I would be happy to contribute 1$ per month. @AliOsm , have you considered setting up [Github Sponsor](https://github.com/sponsors) for this repo with a target of 10$ per month?

**Comment by AliOsm** [comment]
Finally, KONTESTS is not running on Heroku anymore!

KONTESTS is now hosted on a Vultr server and deployed using HatchBox. The combination is very cool and smooth. HatchBox is not providing a lot of functionalities like Heroku buildpacks, but it gives you the smooth deployment experinece of Heroku with more flexibility on managing the server. Also, I'm deploying 3 apps with 15$ only now :)

I'm still encouraging you to support open source projects...

I'm still exploring the limitations and fixing some bugs. Thanks for your contribution.
