### ISSUE TITLE
leetcode, codeforces contests are not updating

### ISSUE THREAD

**Issue by mukund0909** [AliOsm/kontests#86]
@AliOsm @ehamamrah @IbraheemTuffaha @ridaomar @Git-Harshit 
leetcode, codeforces contests are not updating

**Comment by AliOsm** [comment]
Hello,

I'm dropping KONTESTS support. It reached its end of life, sorry for this, but I can't maintain it anymore. I will take it off soon, the code is open source, anyone can deploy it anywhere, and I will be very happy to support by migrating the domain name to their account. If anyone wants the website to continue without managing its deployment and code, I'm asking for $15 support per month, and all issues will be solved, as I will return back to Heroku, the original platform I used to develop and host KONTESTS.

**Comment by gurtejrehal** [comment]
@mukund0909 you can use a more simpler scraper to get the contest details and serve it using Flask.
It follow same schema as Kontest.

[programming-contest-scraper](https://github.com/gurtejrehal/programming-contest-scraper/tree/main)

**Comment by mukund0909** [comment]
@gurtejrehal Where to deploy it, which is the best platform which provides free deployment

**Comment by gurtejrehal** [comment]
@mukund0909 Its a flask app, so you can deploy it on [pythonanywhere](https://pythonanywhere.com/), it would be simple.
And schedule cron job for `scraper.py` to get up-to-date everyday.
