### ISSUE TITLE
Failing to connect. Please assist

### ISSUE THREAD

**Issue by MuzavaziTawa** [AliOsm/kontests#87]
This site can’t be reachedCheck if there is a typo in kontests.net.
If spelling is correct, [try running Windows Network Diagnostics](javascript:diagnoseErrors()).
DNS_PROBE_FINISHED_NXDOMAIN

**Comment by AliOsm** [comment]
Hello @MuzavaziTawa,

I'm dropping KONTESTS support. It reached its end of life, sorry for this, but I can't maintain it anymore. I will take it off soon, the code is open source, anyone can deploy it anywhere, and I will be very happy to support by migrating the domain name to their account. If anyone wants the website to continue without managing its deployment and code, I'm asking for $15 support per month, and all issues will be solved, as I will return back to Heroku, the original platform I used to develop and host KONTESTS.

Best Regards,
Ali Fadel
